default_platform(:ios)

before_all do
	sh 'mkdir ../reports || true'
	sh 'mkdir ../dist || true'
end

desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
lane :lint do
  swiftlint(
      mode: :lint,
      output_file: 'reports/swiftlint.txt',
      config_file: 'fastlane/.swiftlint.yml'
    )
end
  
  
desc "Run unit tests."
lane :tests do
   run_tests(workspace: "GBSwiftLogger.xcworkspace",
            devices: ["iPhone 8"],
            scheme: "GBSwiftLogger",
	   clean: true)
end

lane :changelog do |options|
changelog_from_git_commits(
	between: [options[:tag],"HEAD"],
  	pretty: "* %b [%aN]",# Optional, lets you provide a custom format to apply to each commit when generating the changelog text
  	date_format: "short",# Optional, lets you provide an additional date format to dates within the pretty-formatted string
  	match_lightweight_tag: false,  # Optional, lets you ignore lightweight (non-annotated) tags when searching for the last tag
  	merge_commit_filtering: "only_include_merges" # Optional, lets you filter out merge commits
)
changelog = lane_context[SharedValues::FL_CHANGELOG]

sh("echo CHANGELOG=${changelog} >> $GITHUB_ENV")

end
