name: fastlane
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: fastlane
    runs-on: macos-latest

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true

    - name: Setup Fastlane
      run:  |
          bundle install

    - name: Install Pods
      run:  |
          pod install

    - shell: bash
      env:
          GB_SWIFT_LOG_ENV_USER: ${{ secrets.GB_SWIFT_LOG_ENV_USER }}
          GB_SWIFT_LOG_ENV_PASSWORD: ${{ secrets.GB_SWIFT_LOG_ENV_PASSWORD }}
          GB_SWIFT_LOG_ENV_TOKEN: ${{ secrets.GB_SWIFT_LOG_ENV_TOKEN }}
      run:  |
          sh setup_env.sh -u "$GB_SWIFT_LOG_ENV_USER" -p "$GB_SWIFT_LOG_ENV_PASSWORD" -t "$GB_SWIFT_LOG_ENV_TOKEN"

    - name: Sleep for 10 seconds
      run: |
          sleep 10

    - name: Run tests 
      run: |
          bundle exec fastlane tests
        
    - name: Run Swift lint 
      run: |
          bundle exec fastlane lint
