name: fastlane_changelog
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: fastlane_changelog
    runs-on: macos-latest

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true

    - name: Setup Fastlane
      run:  |
          bundle install

    - name: bash
      run:  |
          echo "LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV


    - name: Run tests 
      run: |
          echo "CHANGELOG=$(bundle exec fastlane changelog ${{ env.LAST_TAG }})" >> $GITHUB_ENV

    - name: Print Changelog
      run: |
          echo "${{ env.CHANGELOG }}"
