name: fastlane_changelog
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: fastlane_changelog
    runs-on: macos-latest

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true

    - name: Setup Fastlane
      run:  |
          bundle install

    - name: Get last created TAG
      id: get-last-tag
      run:  echo "::set-output name=LAST_TAG::$(git describe --tags $(git rev-list --tags --max-count=1))"


    - name: Get changelog from last TAG 
      id: get-changelog
      run: |
          echo "::set-output name=CHANGELOG::$(bundle exec fastlane changelog tag:${{ steps.get-last-tag.outputs.LAST_TAG }})"

    - name: Print Changelog
      run: |
          echo "${{ steps.get-changelog.outputs.CHANGELOG }}"
