name: ios_fastlane_gha 
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: Fastlane 
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
        bundler-cache: true

    - name: Setup Fastlane
      run:  |
          bundle install
    - name: Install Pods
      run:  |
        pod install
            
    - name: Run tests 
      run: |
        bundle exec fastlane tests
    - name: Run App 
      run: |
        bundle exec fastlane demo_app
        
    - name: Run Swift lint 
      run: |
        bundle exec fastlane lint