name: PublishDocumentation

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        args: "--clean --author Guillermo Battistel --podspec GBSwiftLogger.podspec --output docs/swift_output"
