name: jazzy_docs
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: jazzy_docs
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true

    - name: Install Pods
      run:  |
          pod install

    - name: Install jazzy
      run:  |
          gem install jazzy

    - name: Run jazzy
      run:  |
          jazzy \
            --clean \
            --author Guillermo Battistel \
            --author_url https://github.com/gbattistel \
            --xcodebuild-arguments -workspace,GBSwiftLogger.xcworkspace,-scheme,GBSwiftLogger,-sdk,iphoneos \
            --output docs/swift_output
            
    - name: Commit changes
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Jazzy docs updated"
          git push
