name: release_create_github_release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'     
        required: true
        default: '0.0.0'
jobs:
  tests:
    name: release_create_github_release
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: "✏️ Generate release changelog"
      id: generate-release-changelog
      uses: Bullrich/generate-release-changelog@master
      env:
          REPO: ${{ github.repository }}
      with:
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: "🚀 Create GH Release"
      id: release
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        body: ${{ steps.generate-release-changelog.outputs.changelog }}
        draft: false
        prerelease: false
